language: php

php:
  - 7.4
  - 8.0
  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
